- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_taps:
      - caskroom/cask
    homebrew_packages:
      - { name: ansible }
      - { name: autoconf }
      - { name: brew-cask }
      - { name: coreutils }
      - { name: cscope }
      - { name: ctags }
      - { name: curl }
      - { name: emacs }
      - { name: freetype }
      - { name: gdbm }
      - { name: git }
      - { name: imagemagick }
      - { name: jenkins }
      - { name: jpeg }
      - { name: libevent }
      - { name: libpng }
      - { name: libtool }
      - { name: libyaml }
      - { name: lua }
      - { name: macvim }
      - { name: node }
      - { name: openssl }
      - { name: pcre }
      - { name: pkg-config }
      - { name: python }
      - { name: rbenv }
      - { name: readline }
      - { name: rsense }
      - { name: ruby-build }
      - { name: scala }
      - { name: sqlite }
      - { name: the_silver_searcher }
      - { name: tig }
      - { name: tmux }
      - { name: tree }
      - { name: typesafe-activator }
      - { name: vim }
      - { name: wget }
      - { name: xz }
      - { name: zsh-completions }
    homebrew_cask_packages:
      - { name: atom }
      - { name: dropbox }
      - { name: eclipse-jee }
      - { name: emacs }
      - { name: evernote }
      - { name: filezilla }
      - { name: firefox }
      - { name: google-chrome }
      - { name: google-drive }
      - { name: heroku-toolbelt }
      - { name: iterm2 }
      - { name: java }
      - { name: karabiner }
      - { name: macvim }
      - { name: slack }
      - { name: sourcetree }
      - { name: sublime-text }
      - { name: vagrant }
      - { name: virtualbox }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: name={{ item.name }} state={{ item.state|default('latest') }} install_options={{ item.install_options|default() }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
